[project]
name = "dummy-image-generator"
version = "0.1.0"
description = "運転免許証のダミー画像生成ツール"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]

[tool.ruff]
line-length = 120